# Generated by Django 2.2.17 on 2021-03-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasecontractdetail',
            old_name='cd_num',
            new_name='pcd_num',
        ),
        migrations.RenameField(
            model_name='purchasecontractdetail',
            old_name='cd_pr_identify',
            new_name='pcd_pr_identify',
        ),
        migrations.RenameField(
            model_name='purchasecontractdetail',
            old_name='cd_prd_remarks',
            new_name='pcd_prd_remarks',
        ),
        migrations.RenameField(
            model_name='purchasecontractdetail',
            old_name='cd_sum',
            new_name='pcd_sum',
        ),
        migrations.RenameField(
            model_name='purchasecontractdetail',
            old_name='cd_taxRate',
            new_name='pcd_taxRate',
        ),
        migrations.RenameField(
            model_name='purchasecontractdetail',
            old_name='cd_tax_price',
            new_name='pcd_tax_price',
        ),
        migrations.RenameField(
            model_name='purchasecontractdetail',
            old_name='cd_tax_sum',
            new_name='pcd_tax_sum',
        ),
        migrations.RenameField(
            model_name='purchasecontractdetail',
            old_name='cd_tax_unitPrice',
            new_name='pcd_tax_unitPrice',
        ),
        migrations.RenameField(
            model_name='purchasecontractdetail',
            old_name='cd_unitPrice',
            new_name='pcd_unitPrice',
        ),
        migrations.RenameField(
            model_name='purchasecontractdetail',
            old_name='cd_used',
            new_name='pcd_used',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='cd_detail',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='pr_detail',
        ),
        migrations.AlterField(
            model_name='purchasecontractdetail',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_pcd', to='base.Material', verbose_name='物料'),
        ),
        migrations.AlterField(
            model_name='purchasecontractdetail',
            name='purchase_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_pcd', to='purchase.PurchaseContract', verbose_name='采购合同'),
        ),
        migrations.AlterModelTable(
            name='purchasecontractdetail',
            table='db_purchase_contract_detail',
        ),
        migrations.AlterModelTable(
            name='purchasecontractpaydetail',
            table='db_purchase_contract_pay_detail',
        ),
        migrations.AlterModelTable(
            name='purchaseorder',
            table='db_purchase_order',
        ),
    ]
