# Generated by Django 2.2.17 on 2021-03-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseRequest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='pr_closeReason',
            new_name='prq_closeReason',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='pr_closed_at',
            new_name='prq_closed_at',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='pr_closer',
            new_name='prq_closer',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='pr_closer_identify',
            new_name='prq_closer_identify',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='pr_created_at',
            new_name='prq_created_at',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='pr_creator',
            new_name='prq_creator',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='pr_creator_identify',
            new_name='prq_creator_identify',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='pr_date',
            new_name='prq_date',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='pr_department',
            new_name='prq_department',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='pr_identify',
            new_name='prq_identify',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='pr_remarks',
            new_name='prq_remarks',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='pr_serial',
            new_name='prq_serial',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='pr_status',
            new_name='prq_status',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='pr_type',
            new_name='prq_type',
        ),
        migrations.RenameField(
            model_name='purchaserequestdetail',
            old_name='pr_identify',
            new_name='prq_identify',
        ),
        migrations.RenameField(
            model_name='purchaserequestdetail',
            old_name='prd_num',
            new_name='prqd_num',
        ),
        migrations.RenameField(
            model_name='purchaserequestdetail',
            old_name='prd_present_num',
            new_name='prqd_present_num',
        ),
        migrations.RenameField(
            model_name='purchaserequestdetail',
            old_name='prd_remarks',
            new_name='prqd_remarks',
        ),
        migrations.RenameField(
            model_name='purchaserequestdetail',
            old_name='prd_used',
            new_name='prqd_used',
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_prq', to='base.Organization', verbose_name='组织'),
        ),
        migrations.AlterField(
            model_name='purchaserequestdetail',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_prqd', to='base.Material', verbose_name='物料'),
        ),
        migrations.AlterField(
            model_name='purchaserequestdetail',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prq_prqd', to='purchaseRequest.PurchaseRequest', verbose_name='请购单'),
        ),
        migrations.AlterModelTable(
            name='purchaserequest',
            table='db_purchase_request',
        ),
        migrations.AlterModelTable(
            name='purchaserequestdetail',
            table='db_purchase_request_detail',
        ),
    ]
