# Generated by Django 2.2.17 on 2021-03-06 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_present_num', models.IntegerField(verbose_name='物料现存量')),
                ('ts_present_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='库存单价')),
                ('ts_present_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='库存总额')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_ts', to='base.Material', verbose_name='物料')),
                ('totalwarehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_ware_house_ts', to='base.TotalWareHouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '仓库',
                'db_table': 'db_total_stock',
            },
        ),
    ]
