# Generated by Django 2.2.17 on 2021-03-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=20, verbose_name='权限名字')),
            ],
            options={
                'verbose_name': '权限',
                'db_table': 'db_permission',
            },
        ),
    ]
