# Generated by Django 2.2.17 on 2021-03-06 16:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyInStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bis_identify', models.CharField(max_length=15, verbose_name='入库单编号')),
                ('bis_serial', models.CharField(max_length=4, verbose_name='入库单流水号')),
                ('bis_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='采购入库日期')),
                ('bis_remarks', models.TextField(max_length=400, verbose_name='采购入库单备注')),
                ('bis_status', models.IntegerField(choices=[(0, '草稿'), (1, '已审批')], default=0, verbose_name='采购入库单状态')),
                ('bis_creator', models.CharField(max_length=20, verbose_name='采购入库单创建人名字')),
                ('bis_creator_identify', models.CharField(max_length=20, verbose_name='采购入库单创建人工号')),
                ('bis_created_at', models.DateTimeField(auto_now_add=True, verbose_name='采购入库单创建日期')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_bis', to='base.Organization', verbose_name='组织')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_bis', to='base.Supplier', verbose_name='供应商')),
                ('totalwarehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_wh_bis', to='base.TotalWareHouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '材料出库单',
                'verbose_name_plural': '材料出库单',
                'db_table': 'db_bis',
            },
        ),
        migrations.CreateModel(
            name='OtherStoreIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('osi_identify', models.CharField(max_length=15, verbose_name='其它入库单编号')),
                ('osi_serial', models.CharField(max_length=4, verbose_name='其它入库单流水号')),
                ('osi_wh', models.CharField(max_length=15, verbose_name='其它入库仓库名字')),
                ('osi_type', models.IntegerField(choices=[(0, '转库入库'), (1, '盘盈出库')], verbose_name='其它入库单类型')),
                ('osi_date', models.DateField(auto_now_add=True, verbose_name='其它出库日期')),
                ('osi_remarks', models.TextField(max_length=400, verbose_name='其它出库单备注')),
                ('osi_status', models.IntegerField(choices=[(0, '草稿'), (1, '已审批')], default=0, verbose_name='其它出库单状态')),
                ('osi_creator', models.CharField(max_length=20, verbose_name='其它出库单创建人')),
                ('osi_createDate', models.DateTimeField(auto_now_add=True, verbose_name='其它出库单创建日期')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_osi', to='base.Organization', verbose_name='组织')),
            ],
            options={
                'verbose_name': '其它入库单',
                'verbose_name_plural': '其它入库单',
                'db_table': 'db_other_storein',
            },
        ),
        migrations.CreateModel(
            name='OtherStoreInDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('osid_paper_num', models.IntegerField(verbose_name='应收数量')),
                ('osid_real_num', models.IntegerField(verbose_name='实收数量')),
                ('osid_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='无税单价')),
                ('osid_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='无税总额')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_osid', to='base.Material', verbose_name='物料')),
                ('other_si', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osi_osid', to='storein.OtherStoreIn', verbose_name='其它入库单')),
            ],
            options={
                'verbose_name': '其它入库单详情',
                'verbose_name_plural': '其它入库单详情',
                'db_table': 'db_other_storein_detail',
            },
        ),
        migrations.CreateModel(
            name='BuyInStoreDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bd_paper_num', models.IntegerField(verbose_name='应入库数量')),
                ('bd_real_num', models.IntegerField(verbose_name='实际入库数量')),
                ('bd_unitPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='无税单价')),
                ('bd_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='无税总额')),
                ('po_identify', models.CharField(max_length=15, verbose_name='采购订单号')),
                ('pr_identify', models.CharField(max_length=15, verbose_name='请购订单号')),
                ('buy_in_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bis_bd', to='storein.BuyInStore', verbose_name='采购入库单')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_bd', to='base.Material', verbose_name='物料')),
            ],
            options={
                'verbose_name': '采购入库单明细',
                'verbose_name_plural': '采购入库单明细',
                'db_table': 'db_bis_detail',
            },
        ),
    ]
