# Generated by Django 2.2.17 on 2021-03-06 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_permission'),
        ('storein', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPurchaseReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oprc_identify', models.CharField(max_length=15, verbose_name='其它入库单编号')),
                ('oprc_serial', models.CharField(max_length=4, verbose_name='其它入库单流水号')),
                ('oprc_wh', models.CharField(max_length=15, verbose_name='其它入库仓库名字')),
                ('oprc_type', models.IntegerField(choices=[(0, '转库入库'), (1, '盘盈出库')], verbose_name='其它入库单类型')),
                ('oprc_date', models.DateField(auto_now_add=True, verbose_name='其它出库日期')),
                ('oprc_remarks', models.TextField(max_length=400, verbose_name='其它出库单备注')),
                ('oprc_status', models.IntegerField(choices=[(0, '草稿'), (1, '已审批')], default=0, verbose_name='其它出库单状态')),
                ('oprc_creator', models.CharField(max_length=20, verbose_name='其它出库单创建人')),
                ('oprc_created_at', models.DateTimeField(auto_now_add=True, verbose_name='其它出库单创建日期')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_oprc', to='base.Organization', verbose_name='组织')),
            ],
            options={
                'verbose_name': '其它入库单',
                'verbose_name_plural': '其它入库单',
                'db_table': 'db_other_purchase_receipt',
            },
        ),
        migrations.CreateModel(
            name='OtherPurchaseReceiptDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oprcd_paper_num', models.IntegerField(verbose_name='应收数量')),
                ('oprcd_real_num', models.IntegerField(verbose_name='实收数量')),
                ('oprcd_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='无税单价')),
                ('oprcd_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='无税总额')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_oprcd', to='base.Material', verbose_name='物料')),
                ('other_prc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oprc_oprcd', to='storein.OtherPurchaseReceipt', verbose_name='其它入库单')),
            ],
            options={
                'verbose_name': '其它入库单详情',
                'verbose_name_plural': '其它入库单详情',
                'db_table': 'db_other_purchase_receipt_detail',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prc_identify', models.CharField(max_length=15, verbose_name='入库单编号')),
                ('prc_serial', models.CharField(max_length=4, verbose_name='入库单流水号')),
                ('prc_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='采购入库日期')),
                ('prc_remarks', models.TextField(max_length=400, verbose_name='采购入库单备注')),
                ('prc_status', models.IntegerField(choices=[(0, '草稿'), (1, '已审批')], default=0, verbose_name='采购入库单状态')),
                ('prc_creator', models.CharField(max_length=20, verbose_name='采购入库单创建人名字')),
                ('prc_creator_identify', models.CharField(max_length=20, verbose_name='采购入库单创建人工号')),
                ('prc_created_at', models.DateTimeField(auto_now_add=True, verbose_name='采购入库单创建日期')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_prc', to='base.Organization', verbose_name='组织')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prc', to='base.Supplier', verbose_name='供应商')),
                ('totalwarehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_wh_prc', to='base.TotalWareHouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '材料出库单',
                'verbose_name_plural': '材料出库单',
                'db_table': 'db_purchase_receipt',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prcd_paper_num', models.IntegerField(verbose_name='应入库数量')),
                ('prcd_real_num', models.IntegerField(verbose_name='实际入库数量')),
                ('prcd_unitPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='无税单价')),
                ('prcd_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='无税总额')),
                ('po_identify', models.CharField(max_length=15, verbose_name='采购订单号')),
                ('prq_identify', models.CharField(max_length=15, verbose_name='请购订单号')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_prcd', to='base.Material', verbose_name='物料')),
                ('purchase_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_prcd', to='storein.PurchaseReceipt', verbose_name='采购入库单')),
            ],
            options={
                'verbose_name': '采购入库单明细',
                'verbose_name_plural': '采购入库单明细',
                'db_table': 'db_purchase_receipt_detail',
            },
        ),
        migrations.RemoveField(
            model_name='buyinstoredetail',
            name='buy_in_store',
        ),
        migrations.RemoveField(
            model_name='buyinstoredetail',
            name='material',
        ),
        migrations.RemoveField(
            model_name='otherstorein',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='otherstoreindetail',
            name='material',
        ),
        migrations.RemoveField(
            model_name='otherstoreindetail',
            name='other_si',
        ),
        migrations.DeleteModel(
            name='BuyInStore',
        ),
        migrations.DeleteModel(
            name='BuyInStoreDetail',
        ),
        migrations.DeleteModel(
            name='OtherStoreIn',
        ),
        migrations.DeleteModel(
            name='OtherStoreInDetail',
        ),
    ]
